spring.application.name=career-backend
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/career_database
spring.datasource.username=root
spring.datasource.password=Harshith@2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
# Use a secure secret key in production!
jwt.secret=7d825a072462e7ccbae6a68f6dd0f40ab3608cc0662d5143a509ed9eeb55db52
jwt.expiration=86400000

# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
